[package]

name = "headers-derive"
version = "0.0.0" # don't forget to update html_root_url
description = "derive(Header)"
authors = ["Sean McArthur <sean@seanmonstar.com>"]

[lib]
name = "headers_derive"
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"
