[package]

name = "headers-ext"
version = "0.0.0" # don't forget to update html_root_url
description = "typed HTTP headers"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT"

[dependencies]
bytes = "0.4"
headers-core = { path = "../headers-core" }
headers-derive = { path = "../headers-derive" }
http = "0.1.11"
time = "0.1"
